sudo: required
services:
  - docker

before_install:
  - docker build -t umakanuri/docker-react -f Dockerfile.dev .

script:
  - docker run umakanuri/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-088745045272"
  bucket_path:"docket-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
